### ISSUE TITLE
more files need be sent - solved

### ISSUE THREAD

**Issue by Ron2014** [dawidd6/action-send-mail#1]
when I build fail in github actions, cmake create two log files.  I wrote this:

```
    - name: Send mail
      uses: dawidd6/action-send-mail@master
      with:
        serveraddress: smtp.163.com
        serverport: 465
        username: ${{ secrets.MAILUSERNAME_LOG }}
        password: ${{ secrets.MAILPASSWORD_LOG }}
        subject: Error log for cmake
        body: 
          - file://cpp/trunk/fips-build/code/windows/CMakeFiles/CMakeOutput.log
          - file://cpp/trunk/fips-build/code/windows/CMakeFiles/CMakeError.log
        to: dev_ron@163.com
        from: GitHub Actions
        content_type: text/html
```

and recieve error:

```
### ERRORED 07:18:29Z

- Your workflow file was invalid: The pipeline is not valid. .github/workflows/windows.yml (Line: 28, Col: 11): A sequence was not expected
```

So, how to write when I need TWO or MORE FILES to be sent???
