### ISSUE TITLE
[feature] send mail without autorization using my own server

### ISSUE THREAD

**Issue by pioneer19** [dawidd6/action-send-mail#10]
I want to be able to send e-mails to my domain using my server without authentication. Please add this feature.

Currently I got error
`##[error]Input required and not supplied: username`
My config is
```
- name: Send mail
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: my.mx.server.com
          server_port: 25
          username: null
          password: null
          subject: Github Actions job result
          # Literal body:
          body: Build job of ${{github.repository}} completed successfully!
          # Read file contents as body:
          to: mail@server.com
          from: <>
          # Optional content type (defaults to text/plain):
          content_type: text/plain
```
