### ISSUE TITLE
Composing hyperlink in email body using Markdown

### ISSUE THREAD

**Issue by ciprian-shoreline** [dawidd6/action-send-mail#121]
Hey,

I tried to compose a hyperlink in the email body but didn't work.

I tried this:
```
...
body: [google](https://google.com)
convert_markdown: true
```

My expectation is to see something like this: [google](https://google.com)

Any idea how to do that?

**Comment by charlie-cadmv** [comment]
Change the syntax in your question to use `html_body` instead of `body`. Then Markdown conversion will work. It would be easier for new users if `body` were just removed, but it's probably around to support existing use.

**Comment by ryeleo** [comment]
Strangly, it looks like `html_body` is not rendering the MD hyperlinks either.

![Image](https://github.com/user-attachments/assets/e8ef7b36-37f4-4eb4-a907-c39f6ddd6950)

```
    -
      name: Send email
      uses: dawidd6/action-send-mail@abb4c87fd6f434096df2720401389e1f587bd2f5
      with:
        html_body: |
            This is a test email sent by [gh-actions-send-email GitHub Action](${{ env.WORKFLOW_RUN_URL }}).
        to: ${{ inputs.to }}
        attachments: ${{ inputs.attachments }}
        subject: ${{ inputs.subject }}
        from: ${{ inputs.from }} 
        connection_url: smtp://${{ inputs.server }}:${{ inputs.port }}
        secure: true  # Ensure we use TLS (STARTTLS)
        convert_markdown: true

```
