### ISSUE TITLE
How to use SES to send emails for job failure

### ISSUE THREAD

**Issue by Muneeshbiologit** [dawidd6/action-send-mail#122]
I am using the below code snippet for sending emails for action status using AWS SES. But i am keep facing issue fro from address

 ```
 if: always()
      uses: dawidd6/action-send-mail@v3
      with:
        # mail server settings
        server_address: ${{secrets.SMTP_HOST}}
        server_port: 465
        # Optional (recommended): mail server username:
        username: ${{secrets.SMTP_USERNAME}}
        # Optional (recommended) mail server password:
        password: ${{secrets.SMTP_PASSWORD}}
        # email subject
        subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
        # email body as text
        body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
        # comma-separated string, send email to
        to: test@example.com
        # from email name
        from: test@example.com
```
