### ISSUE TITLE
Body can't find file

### ISSUE THREAD

**Issue by marcodelmoral** [dawidd6/action-send-mail#129]
Action fails, cant find body file. readme.md file is in the root of the repo.

```

name: Email
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: 42069
          to: ayy@lmao.com
          from: mmmmm
          secure: true
          body: file://readme.md
          ignore_cert: true
          convert_markdown: true
          attachments: ./*.pdf
          priority: normal

```
