### ISSUE TITLE
Error: Unexpected socket close

### ISSUE THREAD

**Issue by thewolf25** [dawidd6/action-send-mail#144]
Hello , i have put all the information of my account and i got "Error: Unexpected socket close" .

**Comment by jasonm23** [comment]
Hi @thewolf25 could you provide your settings?

**Comment by dilansalinda** [comment]
Got the same after Google account security section settings are configured

Enable 2 factor authentication and added google App password.

```
Run dawidd6/action-send-mail@v3
  with:
    server_address: smtp.gmail.com
    server_port: 465
    secure: true,
    username: ***
    password: ***
    subject: AutoMobile Seeker
    to: ***
    from: AutoMobile Seeker
    html_body: file://data.md
    convert_markdown: true
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.9.16/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.9.16/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.9.16/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.9.16/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.9.16/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.16/x64/lib
  
Error: Unexpected socket close
```

**Comment by dilansalinda** [comment]
> Hi @thewolf25 could you provide your settings?

Hi @jasonm23 here are settings

   ```
-  name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true,
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: 'AutoMobile Seeker'
          to: dilan2012salinda@gmail.com
          from: kubesonar@gmail.com
          html_body: file://data.md
          convert_markdown: true

```
