### ISSUE TITLE
Templating?

### ISSUE THREAD

**Issue by seanhandley** [dawidd6/action-send-mail#15]
Hi,

Is it possible to set the `body` value to a file and have values interpolated within it?

i.e.

```yaml
# workflow.yml
    - name: Notify Email
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.MAIL_USERNAME }}
        password: ${{ secrets.MAIL_PASSWORD }}
        subject: Test
        body: file://templates/test.html
        to: ${{ env.email_address }}
        from: Test
        content_type: text/html
```

```html
# templates/test.html
<p>Hello ${{ env.name }} !</p>
```

I've tried this directly but it doesn't interpolate the values.
