### ISSUE TITLE
Can't send email

### ISSUE THREAD

**Issue by John4650-hub** [dawidd6/action-send-mail#155]
I have followed every step as shown in the example from the readme but the job fails with error that `Username and password not specified`
Here is my full workflow
```yaml
name: Send Job Logs to Email

on:
  push:
    branches:
      - master

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get the log output
      run: | 
       echo "Job Logs"
       ls
       apt list 

    - name: Send log output to email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 25 
        username: ${{secrets.EMAIL_ADD}}
        password: ${{secrets.PWD_EMAIL}}
        from: james
        to: johnpatrick@gmail.com
        subject: Job Logs - ${{ env.GITHUB_REPOSITORY }}
        body: |
          Logs: ${{ steps.Get_the_log_output.outputs.logs }}        

```
