### ISSUE TITLE
The mail is sent without the attachement

### ISSUE THREAD

**Issue by Nawi98** [dawidd6/action-send-mail#166]
Hello everyone ! 
The final aim of my worflow is to sent my artifact by mail : 
Here is my workflow : 
<img width="683" alt="to_github" src="https://github.com/dawidd6/action-send-mail/assets/87074904/989a462a-d617-4347-990d-ccf1a710b7d5">

``

The mail is sent correctly but I do not see any attachment in it : 
<img width="580" alt="mail_sent" src="https://github.com/dawidd6/action-send-mail/assets/87074904/e6c15a05-97be-48bd-860a-a23127bf57ba">

Any thought about it please?
Regards.

**Comment by dawidd6** [comment]
Is this windows runner? I haven't tested this action on windows at all.

**Comment by Nawi98** [comment]
Hello, I made some changes in my code, here it is now : 

```
on: workflow_dispatch 
 
jobs:
  run_manual : # run my test
    runs-on: ubuntu-latest
    steps:
      - name: run the Testim s tests with Testim s gitHub action
        #id: tests_ok_ko
        uses: instinctstudios/testim-cli-gh-action@v0.6.0
        continue-on-error: true
        with:
          token: ${{ secrets.TESTIM_TOKEN }} 
          project: ${{ secrets.PROJECT_ID }} 
          grid: Testim-Grid
          suite: to_test_github_integration

      
          
      - name: upload the artifact generated by Testim itself
        uses: actions/upload-artifact@v3
        with:
          name: test_report
          path: /home/runner/work/launch_testim_tests/launch_testim_tests/testim-report.xml
          if-no-files-found: warn
      
      

      - name: parse the file
        run: cat ./testim-report.xml | grep -i -C 1 "<failure" | tee final-report.xml

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          secure: true
          username: ${{ secrets.MAIL }}
          password: ${{ secrets.PASSWORD }}
          subject: "XML File"
          to: my_mail_address@gmail.com
          from: Testim user
          body: Please find the report of Testim tests attached.
          attachments: final-report.xml
          
      
```

But unfortunately, the file is not received .
