### ISSUE TITLE
Underscore in URL breaks links in google groups

### ISSUE THREAD

**Issue by NotMyFault** [dawidd6/action-send-mail#171]
Hey,

I'm using the following setup:
```yaml
jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          secure: true
          subject: ${{ github.event.release.tag_name }} has been released
          to: demo@googlegroups.com
          from: Release Bot
          html_body: ${{ github.event.release.body }}
          convert_markdown: true
```
with this release text:
```md
Download the release from: https://repo.jenkins-ci.org/incrementals/org/jenkins-ci/main/jenkins-war/2.401.3-rc33578.5f3947a_c72fc/jenkins-war-2.401.3-rc33578.5f3947a_c72fc.war
```
but the underscore (`7a_c`) breaks the rendering of the URL in the message posted in google groups:
![Screenshot 2023-07-19 at 08 56 44](https://github.com/dawidd6/action-send-mail/assets/13383509/5bb636a8-a9d0-4f48-a3b0-b1e7109b83ef)
Everything else looks good as intended.
