### ISSUE TITLE
Error ssl3_get_record wrong version number

### ISSUE THREAD

**Issue by clemdesign** [dawidd6/action-send-mail#187]
When I run the action job, I have this error:

> 140327535802304:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:

With this job configuration:

```
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          secure: true
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Test
          to: email@domain.ext
          from: Test User
          body: Test
```
