### ISSUE TITLE
Not really an issue but rather an ask...

### ISSUE THREAD

**Issue by Rickcau** [dawidd6/action-send-mail#189]
Can you provide an example in the readme of using Hotmail.com, Live.com, outlook.com email addresses?  I have tried all the various SMTP settings that I can find online and nothing works for these servers.  It would be great to have options other than gmail.

**Comment by EmanuelaBoros** [comment]
Same question.

**Comment by dawidd6** [comment]
I will gladly accept a PR adding those examples 🙂

**Comment by IgnacioHeredia** [comment]
I had the same problem. I ended up calling a [custom Python script](https://gist.github.com/IgnacioHeredia/5f8fd2fc7d56763e4060c7b8fc8e0212) I wrote.
The weird thing is that the _exact same configuration_ worked for the Python script (step 1) but not for this action (step 2):

```yml
    steps:
      - name: Send mail python
        run: |
          curl -s https://gist.githubusercontent.com/IgnacioHeredia/5f8fd2fc7d56763e4060c7b8fc8e0212/raw/3b5915cf3b8e0fd3c67b7ef7a019175116f0c367/send_email.py | \
          python - \
          --from_user ${{secrets.FROM_MAIL_USERNAME}} \
          --from_pwd ${{secrets.FROM_MAIL_PASSWORD}} \
          --to_user ${{secrets.TO_MAIL_USERNAME}} \
          --subject "Failed Github workflow"          

      - name: Send mail action
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp-mail.outlook.com
          server_port: 587
          secure: true
          username: ${{secrets.FROM_MAIL_USERNAME}}
          password: ${{secrets.FROM_MAIL_PASSWORD}}
          subject: Failed Github workflow
          to: ${{secrets.TO_MAIL_USERNAME}}
          from: ${{secrets.FROM_MAIL_USERNAME}}
```
