### ISSUE TITLE
Add option to disable TLS

### ISSUE THREAD

**Issue by Misiu** [dawidd6/action-send-mail#2]
While trying to use your action I got this error:
`Error: SSL_connect returned=1 errno=0 state=error: wrong version number`
I've tried adding an option to disable_tls, but then I'm getting this error:
`Error: 504 5.7.4 Unrecognized authentication type`

Sadly I'm not a Ruby programmer, so I can't help with this.

In one of the apps I use (Redmine - it is in Ruby) I have this config:
```
 email_delivery:
    delivery_method: :smtp
    smtp_settings:
      tls: false
      address: mail.example.com
      port: 25
```
ref: (https://guides.rubyonrails.org/action_mailer_basics.html#action-mailer-configuration)

**Comment by dawidd6** [comment]
Can you test this PR: https://github.com/dawidd6/action-send-mail/pull/3
and report back if it worked for you?

Just set `tls: false` in your workflow.

**Comment by Misiu** [comment]
@dawidd6 sadly it didn't work.
I've added code from your PR: https://github.com/dawidd6/action-send-mail/pull/3/files#diff-c29813a897824c369fa11dcadb067a9bR39

I get this error (I mentioned it in my initial message): 

> Error: 504 5.7.4 Unrecognized authentication type

I had similar code in my fork: https://github.com/Misiu/action-send-mail/commit/1560c27e4259d6a8517787542c60e491d8dafd77

**Comment by Misiu** [comment]
> Just set `tls: false` in your workflow and point to the PR branch.

How and where should I do that?
I found a question on StackOverflow: https://stackoverflow.com/questions/36518887/actionmailer-smtp-certificate-verify-failed but they are using `ActionMailer`.

**Comment by dawidd6** [comment]
Like this:

```yaml
- name: Send mail
  uses: dawidd6/action-send-mail@option-tls
  with:
    tls: false
    server_address: smtp.gmail.com
    server_port: 465
    username: ${{secrets.MAIL_USERNAME}}
    password: ${{secrets.MAIL_PASSWORD}}
    subject: Github Actions job result
```
