### ISSUE TITLE
Certification Error while using TLS on port 587 and on port 25

### ISSUE THREAD

**Issue by SID262000** [dawidd6/action-send-mail#215]
Team,

I'm getting the following error on usage of the emailing service on port 587

> Error: 0098C782CB7F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:

I'm also getting a second error on trying the emailing service on port 25

> unable to get local issuer certificate

We don't support port 465 usage on our emailing server.

Can you please investigate this and recommend a solution? Thanks!

**Comment by SID262000** [comment]
Tagging @dawidd6 for review and potential response.

**Comment by silviogutierrez** [comment]
Just tried this with postmarkapp.com, and I have the same issue.

**Comment by dawidd6** [comment]
Did you try setting `secure` input?

**Comment by Aetherinox** [comment]
These are the settings that work for me

```yml
    # port 465
    server_port: 465
    secure: true
    ignore_cert: false
        
    # port 587
    server_port: 587
    secure: false
```

The question is though, if `secure: false`, is their any actual TLS secure going on in the background. Because the last thing I want to do is start sending emails without SSL.
