### ISSUE TITLE
Option to add attachments

### ISSUE THREAD

**Issue by sturman** [dawidd6/action-send-mail#5]
It would be nice to have an option to add attachments to email message, e.g.

```yaml
- name: Send mail
  uses: dawidd6/action-send-mail@v2
  with:
    server_address: smtp.gmail.com
    server_port: 465
    username: ${{secrets.MAIL_USERNAME}}
    password: ${{secrets.MAIL_PASSWORD}}
    subject: Github Actions job result
    # Literal body:
    body: Build job of ${{github.repository}} completed successfully!
    # Read file contents as body:
    body: file://README.md
    to: obiwan@tatooine.com,yoda@dagobah.com
    from: Luke Skywalker # <user@example.com>
    # Optional content type (defaults to text/plain):
    content_type: text/html
    attachments:
      - filename: 'text1.txt'
        content: 'aGVsbG8gd29ybGQh'
        encoding: 'base64'
      - filename: git.diff
      - filename: 'license.txt',
        path: 'https://raw.github.com/nodemailer/nodemailer/master/LICENSE'
```

Note: nodemailer doc about attachments https://nodemailer.com/message/attachments/

**Comment by dawidd6** [comment]
It is not possible to pass YAML arrays and objects as inputs to actions, see:
https://github.community/t5/GitHub-Actions/Structured-inputs-input-objects-and-arrays/td-p/49114
https://github.community/t5/GitHub-Actions/Can-action-inputs-be-arrays/td-p/33776

The option would be to expect a JSON array on this input, but it looks a bit off. Thoughts?

**Comment by sturman** [comment]
Maybe it's just enough to support single filename for now?
```yaml
    ...
    content_type: text/html
    attach_file: 'attachments.zip'
    ...
```
