### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by okaypatrick** [dawidd6/action-send-mail#56]
Trying to configure this action with GSuite Gmail and getting the following error message even though I've configured it to not enforce SSL and ignore invalid certs:

Error: 140308877371264:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:

Anybody else having the same issue?
![Screen Shot 2021-06-01 at 12 59 40 PM](https://user-images.githubusercontent.com/649663/120383050-3c486000-c2d9-11eb-918d-5253444ffacc.png)
![Screen Shot 2021-06-01 at 1 00 06 PM](https://user-images.githubusercontent.com/649663/120383111-4b2f1280-c2d9-11eb-9663-13c2474f4810.png)

**Comment by dawidd6** [comment]
Remove `secure` input completely and try again.

**Comment by okaypatrick** [comment]
Hmm..get a different error now from GMail..

![image](https://user-images.githubusercontent.com/649663/120483689-34370180-c367-11eb-94bf-3b6621ea4e10.png)

**Comment by Flynsarmy** [comment]
Getting the same wrong version number error with [createsend TLS](https://help.campaignmonitor.com/classic-transactional-emails#smtp) port 465.

**Comment by bauergeorg** [comment]
I have the same problem by using ows server of a self-hosted runner:
![image](https://user-images.githubusercontent.com/79077565/136803622-105f2072-5640-4093-a696-c1aaebc3c31a.png)

**Comment by Flynsarmy** [comment]
@bauergeorg Here's my working version. Hope this helps:
```yaml
      - name: Send success email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.api.createsend.com
          server_port: 587
          username: ${{ secrets.MAIL_USER }}
          password: ${{ secrets.MAIL_PASS }}
          subject: ${{github.repository}} deployed successfully!
          # Literal body:
          body: Body goes here
          to: my@email.com
          from: no-reply <no-reply@mydomain.com>
```
