### ISSUE TITLE
Allow globs for attachments

### ISSUE THREAD

**Issue by Simonwep** [dawidd6/action-send-mail#62]
Hey! First of all thanks for this really nice action!

It'd be cool to be able to use globs for attachments:
```yml
- name: Send mail
  uses: dawidd6/action-send-mail@v3
  with:
    attachments: docs/*.pdf # Glob path!
```

This would attach all `.pdf` files in the `./docs` folder as single files.

I see that you're using JavaScript so [glob](https://www.npmjs.com/package/glob) might be something to use here?
