### ISSUE TITLE
Could not find file 'showndown'

### ISSUE THREAD

**Issue by Lefia** [dawidd6/action-send-mail#69]
Hi, I got an error when action built up :

Error:
Could not find file '/home/runner/work/_actions/_temp_ab0eda08-6b5b-44d1-9038-11fc4752310d/_staging/dawidd6-action-send-mail-a1ab281/node_modules/.bin/showdown'.

I used the version  3.

**Comment by XDanny322** [comment]
I am experiencing the same issue, and as a stop gap, am using the prior verrsion, by changing

```
      - name: E-Mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: mail.xx.com
          server_port: 25
          from: xx@xx.com
          to: ${{ github.actor }}@xx.com
          convert_markdown: true
          subject: xx
          html_body: file://.github/workflows/scripts/app_yaml/fields/email.md
```

to 

```
      - name: E-Mail
        uses: dawidd6/action-send-mail@v3.2.0
        with:
          server_address: mail.xx.com
          server_port: 25
          from: xx@xx.com
          to: ${{ github.actor }}@xx.com
          convert_markdown: true
          subject: xx
          html_body: file://.github/workflows/scripts/app_yaml/fields/email.md
```

..namely changed the version from `v3` to `v3.2.0` for the `uses` key.

After that, working again.
