### ISSUE TITLE
How can I retrieve attachment from IMAP Mail Server

### ISSUE THREAD

**Issue by byteshiva** [dawidd6/action-send-mail#72]
How can I retrieve attachments from IMAP Mail Server? 

`${{on.email.outputs.attachments}}` returns empty value. But the fact is I've sent an attachment to the concerned email server from where I'm retrieving data.

```
on:
  email:
    imap:
      host: imap.example.com
      user: ${{secrets.EMAIL_USER}}
      password: ${{secrets.EMAIL_PASSWORD}}

     - name: Send mail via zohomail
        uses: dawidd6/action-send-mail@v3
        with:
          # Required mail server address:
          server_address: smtp.zoho.in
          # Required mail server port:
          server_port: 465
          # Optional (recommended): mail server username:
          username:  ${{secrets.EMAIL_USER}}
          # Optional (recommended) mail server password:
          password: ${{secrets.EMAIL_PASSWORD}}
          # Required mail subject:
          subject: Re ${{(on.email.outputs.subject)}}
          # Required recipients' addresses:
          to:  ${{(on.email.outputs.from.value[0].address)}}
          # Required sender full name (address can be skipped):
          from: ${{ secrets.FROM_EMAIL_ID }}
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          # Optional plain body:
          body: |
                ${{(on.email.outputs.text)}}
          # Optional recipient of the email response:
          reply_to: ${{ secrets.FROM_EMAIL_ID }}
          # Optional unsigned/invalid certificates allowance:
          ignore_cert: true
          # Optional converting Markdown to HTML (set content_type to text/html too):
          convert_markdown: true
          # Optional attachments:
          attachments: ${{(on.email.outputs.attachments)}}
```
