### ISSUE TITLE
Sending emails with iCloud

### ISSUE THREAD

**Issue by jonnitto** [dawidd6/action-send-mail#84]
Hi

I tried to send an email via iCloud:

```yaml
jobs:
  notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to editors
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.mail.me.com
          server_port: 587
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Subject
          to: ${{secrets.MAIL_TO}}
          from: ${{secrets.MAIL_FROM}}
          secure: true
          body: |
            Multi line
            text
          ignore_cert: true
```

I've created an app-specific password (as mentioned here: https://support.apple.com/en-us/HT202304) but I always get the error

```bash
139634851661696:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:
```
