### ISSUE TITLE
html_body is invalid

### ISSUE THREAD

**Issue by fangwei18** [dawidd6/action-send-mail#85]
Got this error from git action.

```
Warning: Unexpected input(s) 'html_body', valid inputs are ['server_address', 'server_port', 'username', 'password', 'subject', 'body', 'to', 'from', 'cc', 'bcc', 'reply_to', 'ignore_cert', 'content_type', 'convert_markdown', 'attachments']
```

**Comment by dawidd6** [comment]
Please show your workflow file contents

**Comment by fangwei18** [comment]
```
steps:
    - name: Send mail
        if: always()
        uses: dawidd6/action-send-mail@v2
        with:
            server_address: smtp.gmail.com
            server_port: 465
            username: ...
            password: ${{ secrets.EMAIL_PASSWORD }}
            subject: ${{ job.status }}
            content_type: text/html
            html_body: file://email.html
            to: ...
            from: ${{ github.repository }} - ${{ github.workflow }} Action
```
